apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photos-certificate
  namespace: personal
spec:
  secretName: photos-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - photos.yorch.cloud
    - fotos.yorch.cloud
