apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hollo-certificate
  namespace: yorch
spec:
  secretName: hollo-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - social.yorch.dev
