apiVersion: apps/v1
kind: Deployment
metadata:
  name: commsrelay
  namespace: yorch-commsrelay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commsrelay
  template:
    metadata:
      labels:
        app: commsrelay
    spec:
      containers:
        - name: commsrelay
          image: registry.yorch.cloud/library/comms-relay:475591b00b589ccc4fd4bd4b1d2964024b271aa4
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: commsrelay-secret
                  key: auth-username
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commsrelay-secret
                  key: auth-password
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: commsrelay-secret
                  key: auth-secret
          resources:
            limits: {}
      imagePullSecrets:
        - name: harbor-secret
