apiVersion: apps/v1
kind: Deployment
metadata:
  name: photos
  labels:
    app: photos
  namespace: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photos
  template:
    metadata:
      name: photos-pod
      labels:
        app: photos
    spec:
      containers:
        - name: photos-container
          image: photoprism/photoprism:latest
          ports:
            - containerPort: 2342
              name: http
          envFrom:
            - secretRef:
                name: photos-secret
                optional: false
          volumeMounts:
            - name: photos-storage
              mountPath: /photoprism/originals
              subPath: originals
            - name: photos-storage
              mountPath: /photoprism/import
              subPath: import
            - name: photos-storage
              mountPath: /photoprism/storage
              subPath: storage
      volumes:
        - name: photos-storage
          persistentVolumeClaim:
            claimName: photos-pvc
