apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-certificate
  namespace: personal
spec:
  secretName: home-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - home.yorch.cloud
