apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-certificate
  namespace: personal
spec:
  secretName: mealie-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - mealie.yorch.cloud
