apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rssfeed-certificate
  namespace: personal
spec:
  secretName: rssfeed-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - feed.yorch.cloud
