apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: v2-certificate
  namespace: yorch
spec:
  secretName: v2-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - v2.yorch.dev
