apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: it-tools-certificate
  namespace: tools
spec:
  secretName: it-tools-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - it-tools.yorch.cloud
