apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools-deployment
  labels:
    app: it-tools
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      name: it-tools-pod
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools-container
          image: corentinth/it-tools
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools-service
  labels:
    app: it-tools
  namespace: tools
spec:
  selector:
    app: it-tools
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools-ingress
  namespace: tools
spec:
  rules:
    - host: it-tools.yorch.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: it-tools-service
                port:
                  number: 80
  tls:
    - hosts:
        - it-tools.yorch.cloud
      secretName: it-tools-certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: it-tools-certificate
  namespace: tools
spec:
  secretName: it-tools-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - it-tools.yorch.cloud
