---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: finances-secret
  namespace: personal
spec:
  encryptedData:
    app-key: AgCJQNstSWvsscgV/vEQpivJXrRx8l1WZ15zpoCis2aZnbrUtr6MrMGao6odniKuek1vm0/3iQ+kYB6sjo+WNSg11kPznyRc6dGcyKpoSBO/RNEg5W5Hfllerg3CaLHPdz6fhLCEPsJU9eARmMbqGQRJ/bObLSzBnvf+v2MPZKCWr8AEda+MrxnR5ja18hfE6r5qaoexmsov1jGYbT1WHPd4pA3KdWIQc1i2lgsxLtJxuYbt+DTpgC3bpqXsy8+XhMoKTnIrvQZz+me4tAzP/bJxl1trnJqscxbzuyrb4s1XojjiSSRYlnUbl8cO0oPK+bWW2mk+ZZXdF5Jg2nGXwHhQ40vVTLgFSzF2MjbgeW7/1ig8PHyIuUyaBX/yDde4h/4euxUjYTROYcbtQXysQ1vWCgUQGErUg4zk0pKhm55Tx3sw5ClzYq5+ycog0fet63vJ7sbYEBzI/FegIFUZEXyBMUMpgHghLdlrs1ZJJhYcp7pl8OwGYmSRcmYTjOrtxMxpNw20NOCJFz+AjO4roDdREvhcQzOh9VIKKjy6MQwdmzBDRRm6/I+qcWjgakgLxeuIX+Iav33XVjIa/e/v/A2hjlFosp17i4u1NtnhcsthZXGMlHfUpIIf6ECDZTSXzxry4hJgDmvN1b20USzJjW9E62EGlmJtTC55VthGR1gkBf3YEO1mZPYLOJg11ecOeIZ+YCZWMyn+TzrSSENwuHWJHlDAZRJhbl4=
    db-password: AgBe4qPWljPjJE8iyyDstycIeanwVjTGdN4o2zcARWWqmDKtLSqlYPO+ffYdp78Q1GKhkbwjfkcEUI3lEfs2KYN4a4YST+MJmnaWGeyuMb8HLlRgGIsNpS+YJiyqNkS60FzePH+ZO0FneWFdEn+1OXb1xQ1dOzt3v4+Jt44SBsjK89IXzUwy4KnDVz5WLYtTQYvM947/JyO6+/TVlnNE9leUvchG1OmWoI6gohBudj2EniUeyJv9uHXnAuLbpzYkm5jJF+2c7cI6an+q2cEm7PagdVv788tybN/OmLOWtQ2wc8TLEgaIrWVWWN9tqY9gEwCoYt+09rs98+TnM+ePekPEAiG27uRQWFfsZDjtuTVIJLtpi7XkVSgz0CQSHbRXKXc4GItghlAQwZr3oF3XBcX1bD4tKianI9Q7LxXAhzzS+rOfxeb6guyKLbcbgYVo0awzELtN7A9uWplAcChAgyb8LphufR+VOnjksTcNcU6LpGpEgVb9vl80XNJEnpisCWRTTzrbuvGbEPTkVIQwYwAnvfjUNO5uJal2hrDef377UncGQflTtuAY1vH5ayDPcmKTzcD6eX07/2my1voA5Onluci+MbpGq+CEq9DSzOylX261z9OiP2mAhpDacUC8vCD5NSfkRIBGUphGSiadpbwxuJUy7TFue1AaGQ23PGYfNPwyPVOtLIVW1C4fmxn3dW9jAbWa8SYB3ODnLfnxDqLPmVYXJd7VURMVE5ZitCnOm/9bFZ5WkxV5veWtPXF6sA==
  template:
    metadata:
      creationTimestamp: null
      name: finances-secret
      namespace: personal
    type: Opaque
