---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: finances-secret
  namespace: personal
spec:
  encryptedData:
    app-key: AgAt41BOjUxoVTD77bAWl2A4dHFMvctDE3zDypATdcjVtIuDQnibsN9K8GJK7ty8mPBEHoSdkvo5Ob/4xSxvoxJyta9GtzDff0EPdj5azuf5KGY3DoOjpbaT/lxnHQ+suy7rwKux6Uq7BEJj9TylCt0jZij5gAvIhucXMK9JJIzqYOTmBQ/bbZoSAQoeZ6sXcKLjruies6l+wn6Xo3P34iyKuG8HpL9YPPDbS9vZjALS3KhGYo/KqJGd5QWp5QirSZwTRWxfOBNHGcM4Xd3m2Of/e46FIGtl0WaeSIP+09g695Gx+aY4VOiUzte9c0ynxYjGyV0XU3V1vXP2iYWbv5KTi7xMjBVipE4GF5nZcg1Innl1v3kYsyBsqy8DPojqhTtsgVAOdEdGJpRMZY7kH2LL7nP+rdnuPkuj5858ibW44lKZwHx5mqhNXJ23vHD55OF/TIVQxceklCIdHR3E7tLYAxLI+5NJjEgj6tSW5TVcY6BWRS36woh5mJQmIZbpmtXoBgYy7cxQkixZGtzp8iUQAI/fxcDF5+6O9+wcBSDrsHtCRYjZXOxraWvOe13FDbRCtN71wMh3co4PzC8hqU8dGjTGNl8OOvSB1GT0N2521R49EtlE2bmHMx8LVR2bxcCH1Fp12BByy5h2ny5LDf9K/1F8Pvzel/LqlWrT8ldY8v4MvLZW2a+Rk5Upm6/ud872uQC0a6X5R4r6ay+phsy9jNZYOh+LF9qxHUR4eRDl2ctb2sq54mqpLMYxaJm7fvI=
    db-password: AgAB/OO6GjrCI/WiNRRxAJVs93t1OkdRaCiHCAD9nSKQrmTe7PNlA5MXofu0FNiGviRoYf7Jdi4Qk0sBNm1ms1F1QtMTjrOTMEu3Pc72bQxw2TWZ8caxXKjJt3SFgwxqW26bHw0RR0UA+VrTparD97UtiIHiGiqhN6bHZaj3CfGNuGur1mLWykHRlN0M8sE4M7fG/FOnPOwmQxTfa/nkFl6yYGPgosJYfOQ+1xewGBMVriUSfmd7DZ0ktCySDajVrLe7ZSHcCMRNXcSFgNaBzXFY4ewHStzcWjywHBFj/fldPyoNP6E4XdQO8gVRc/yP8FbrNDmRV+995j2sdm1vQrEUqXUYipYF5ZZVYQJ71/Inuh8Wr3WhkkHY2OHm8ESS/57iX43YXONpZEgPi3hGCZY8wN9WszO5DhewQIU5zER57ClUrVAMcq4rLrskh6ed6/RVxsPICW68aWF0sLUH6e5mFgZWFJoYYrUsDFVSupWKgV0I9mcnH4njvT//f1i1dWhH6a4pl8rfwg22nDp1iViOTgqMT3IqYbqf4iiHTnpTWlXPGC2a8UMpXZ6FlgY25kHmyEZkRv23FYiBiu81EcZEPT1g1yqlepuT+jkfonYMGT/kiceQED4TuGVweLGSTRJqNEN+z7/KgcPqRgD+ysvXJuGV121W0YrYR+xH1Jn81mSzRUwyFKl852HI3k1Up8kN4nhwj6suEDQ9tfL223fChiQsKGMaU+vB7qbSLhFtwOzHnNZl0CESRxOWyPChfA==
  template:
    metadata:
      creationTimestamp: null
      name: finances-secret
      namespace: personal
