env:
  DEFAULT_LANGUAGE: es_ES
  TZ: "Europe/Madrid"
ingress:
  main:
    enabled: true
    hosts:
      - host: finances.yorch.cloud
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http
