apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: finances-certificate
  namespace: personal
spec:
  secretName: finances-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - finances.yorch.cloud
