apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finances
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://geek-cookbook.github.io/charts/
    chart: geek-cookbook/firefly-iii
    targetRevision: 0.2.2
    helm:
      valueFiles:
        - valuesRepo://values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: personal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://geek-cookbook.github.io/charts/
      chart: geek-cookbook/firefly-iii
      targetRevision: 0.3.0
    - repoURL: https://github.com/JorgeMayoral/yorch.cloud.git
      path: firefly
      targetRevision: main
      ref: valuesRepo
