apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yorch.dev-v2
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: registry.yorch.cloud/yorch.dev/v2:latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/JorgeMayoral/yorch.cloud.git
    targetRevision: main
    path: yorch.dev-v2
  destination:
    server: https://kubernetes.default.svc
    namespace: yorch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
