apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - certificate.yml
  - deployment.yml
  - ingress.yml
  - namespace.yml
  - pv.yml
  - pvc.yml
  - sealed-secret.yml
  - service.yml
