---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    access-key: AgA5wOccyfQNSaeojcJywvF+Kbb/msjbEIjXimA3PvO8VS3/b7mZ0IBr4Y460+FYuHDSa2vAMtVYwPmye/W4hrYYLlyXLe5LwXrc9Il4mDyzIVA4gOsK9b9VlM2bQii5UxHqB+eFsR/cV8493KjB3ak8fk70lNlMku3FbVEh8elc0+3y1had0MKm3I3tW7XiW9uW2uENN9i2VgjdB4u0Fb5J1nxtKPaXK6pEKYRL9zyS6AC8niRM3502ulpDvviKgzrtd89xnC4ockF878o2oQJWiIRbVRJJrSdzFfA5OcNti5mcNGtw4GKedoPlT4hdJ1dZk4L0wMCRaARxJz4lznqPLYaKsrpGiUwTZTtwpVBT+dMtZDuIeT/zPJ6PX/HyOfmtH2DvUW37eKFnETwNdgvd7MYsXB+KwHONd/FJbVeu+luflWGA6s5rPVSRT9DRydpQBEXUQAydqcCPJXuClb6vUhh0473VulnUoeqkPAQd+I5CC+H/qZWO6/MmeLC82KdaQxjZy8SOEkM6K8bpilzbU5FCkRUHmuXicdFFuyyOiwwpvSyVTkznLnarJkjMql2W4uxRtQY/XnhtNbDdj5rYopl0Rs7/2xAQcHrmrNoCF5YQiPvBC6G61V2TAui9a/ETVxPQYWFoQTvndMCscxlEZZrlIFmSysCUJEtt1xMQHKJI6H1Z5fdxgI9lgbC+csTlbxYFRHzfP8jJhHjO0V5xMqz2HqM=
    secret-key: AgB77NeZcedbdnbnVs+8W7xZxgNaWTOFZtgr+rBagL+NaSEyDArlDRjBGDmou2uyFi7Bg9LngKoGC5wRhH9P3ffZhL6iWm6083cN0UhEkEhGKZ4/R9odlKC9BhdP4k1hbL28idr4lu9Mr2PicOTKEQ+jHLaVgcXt+35ApQ+8i2pSRJumG1WndFWhFGRXucokVe9w0IhhyHq4c0/eJhGuAzR2lI32sAlVVPKPH0v1crOcmguLiDnt5IegCWUA4wYjUNwH0ebwzpQWMamYZp4h1gkHB/qwzuPicGoMgco+3wYHU2Jv/4o2ZEgOwjigT2wgd8BM+mVTi1BMobg7ac7j+LquhL5ZgT9qcTGrnu0E3RN1jC9IwXDzKjxY+M65r6yWPUYeMn2mY4Dk7l72cDXyYkqKjP4/kO6e6Fh3VAnmyuxMrs+xrMx8I5eovxdRFwjgxMjhipAHmcpcYU5cLKJvkDUYM5M5kLgZT6A+QIO22koF027EBNe47XgEJSmkIk4+a3pddRzPK5loHLD+XdTKijvfFeFRQCLQLiAMftKJVELS+PYnV11w6IftOfD72equJWAmg1V2Yk8NGYyOnNAzNK3c15OntYdhhB0WQSFezSLCTMkkuo+VgG9x0fo/hOBZ7VCApLutlnCrg49Yi07yeka/guR4SRLIz6lpL/HIM2eSu/4ooU472eGMmcwjiZcGr1mTo6yNgP7doT7ZZ6s854gNG8PUeRGUYVU6/qQVjNUCTvVf8rAdU3OxXyM=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
    type: Opaque
