apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yorchdev-certificate
  namespace: yorch
spec:
  secretName: yorchdev-certificate
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - yorchdev.yorch.cloud
    - yorch.dev
